WaveView Splash
shreyshrey71/SplitPersonality pull request #16
Opened 2020-01-16 14:35 UTC by htg2704

2020-01-18 05:09 UTC, shreyshrey71 requested changes

2020-01-18 05:09 UTC, shreyshrey71 commented on app/build.gradle
> +        applicationId "com.android.split_personality"
dont change this

2020-01-20 13:33 UTC, TejusR commented on app/src/main/res/layout/activity_create_profile.xml
> +    android:textColor="#F8F6F6"
Please do not hardcode. Save the value in Colors.xml and reference it here

2020-01-20 13:38 UTC, TejusR commented on app/src/main/res/layout/activity_create_profile.xml
> +    android:layout_marginTop="700dp"
Do not hardcode layout_marginTop. While using RelativeLayout use android:layout_below and android:layout_above to spe

2020-01-20 13:42 UTC, TejusR commented on app/src/main/res/layout/activity_create_profile.xml
> +        android:layout_marginTop="600dp">
Do not hardcode marginTop. Use layout_below.

2020-01-20 13:42 UTC, TejusR commented on app/src/main/res/layout/activity_create_profile.xml
> +        android:layout_marginTop="220dp"
Do not hardcode layout_marginTop. Use a LinearLayout or RelativeLayout inside the ScrollView.

2020-01-20 13:46 UTC, TejusR reviewed
Do not hardcode colors. Move the color values to Colors.xml and reference it.

2020-01-22 10:02 UTC, closed without merging